### ISSUE TITLE
error on .search_datasets() with '[' and ']' in search_keys

### ISSUE THREAD

**Issue by Marcus-Adair** [sci-ndp/pop-py#10]
When using .search_datasets() with search_terms and search_keys in the parameters, I got an error response when '[' and ']' were in the string of search_keys

**Comment by rbardaji** [comment]
Hi Marcus,
You're correct that the [] in search_keys causes an error. I will fix this bug. In the meantime, you can use . instead of []. For example, instead of using key_1[property_1], you can use key_1.property_1.

Thank you for identifying this bug! I appreciate your feedback.

**Comment by rbardaji** [comment]
Hi Markus, I’ve already fixed this bug, but I’m still making changes to the API. If it happens again, please let me know.
