### ISSUE TITLE
No demo of how to pass in values directly under "Step 2: Enter API Credentials"

### ISSUE THREAD

**Issue by reshmar00** [sci-ndp/pop-py#11]
**Under Step 2: Enter API Credentials--**

There is only one method being demonstrated right now to add in values for the following variables:

- api_base_url
- api_username
- api_password
- api_token

... and that is by following input prompts

**_We should also highlight how to directly add values so users don't need to be prompted each time_**

For example, we could say:

```
# Prompt the user for API credentials
api_base_url = input("Enter the POP API base URL (include http:// or https://): ")
api_username = input("Enter your POP API username: ")
api_password = getpass("Enter your POP API password: ")
api_token=None

# Or add the API credentials directly as strings
api_base_url = "http://simple.url.com"
api_username = "username123"
api_password = "mY_passw0rd"
api_token=None
```

**Comment by rbardaji** [comment]
Thanks for pointing this out. You’ve got a good point—right now, the tutorial only shows how to enter API credentials by prompting the user, and it doesn’t explicitly mention that you can hardcode values if you prefer. The main reason we’re using input prompts here is to avoid embedding sensitive information directly in the code. This is just a best practice, especially if you’re planning to share your notebook or keep it in version control.

That said, this tutorial is meant to demonstrate how to use the library. Still, you can modify your notebook and directly assign values to these variables if that’s more convenient for your workflow. 

Thanks for the feedback!
